import 'package:currency_converter/models/currency.model.dart';

class Bank {
  static Map<String, Currency> _currencies = {
    "USD": Currency(
        symbol: "\$",
        name: "US Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "USD",
        namePlural: "US dollars"),
    "CAD": Currency(
        symbol: "CA\$",
        name: "Canadian Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "CAD",
        namePlural: "Canadian dollars"),
    "EUR": Currency(
        symbol: "€",
        name: "Euro",
        symbolNative: "€",
        decimalDigits: 2,
        rounding: 0,
        code: "EUR",
        namePlural: "euros"),
    "AED": Currency(
        symbol: "AED",
        name: "United Arab Emirates Dirham",
        symbolNative: "د.إ.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "AED",
        namePlural: "UAE dirhams"),
    "AFN": Currency(
        symbol: "Af",
        name: "Afghan Afghani",
        symbolNative: "؋",
        decimalDigits: 0,
        rounding: 0,
        code: "AFN",
        namePlural: "Afghan Afghanis"),
    "ALL": Currency(
        symbol: "ALL",
        name: "Albanian Lek",
        symbolNative: "Lek",
        decimalDigits: 0,
        rounding: 0,
        code: "ALL",
        namePlural: "Albanian lekë"),
    "AMD": Currency(
        symbol: "AMD",
        name: "Armenian Dram",
        symbolNative: "դր.",
        decimalDigits: 0,
        rounding: 0,
        code: "AMD",
        namePlural: "Armenian drams"),
    "ARS": Currency(
        symbol: "AR\$",
        name: "Argentine Peso",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "ARS",
        namePlural: "Argentine pesos"),
    "AUD": Currency(
        symbol: "AU\$",
        name: "Australian Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "AUD",
        namePlural: "Australian dollars"),
    "AZN": Currency(
        symbol: "man.",
        name: "Azerbaijani Manat",
        symbolNative: "ман.",
        decimalDigits: 2,
        rounding: 0,
        code: "AZN",
        namePlural: "Azerbaijani manats"),
    "BAM": Currency(
        symbol: "KM",
        name: "Bosnia-Herzegovina Convertible Mark",
        symbolNative: "KM",
        decimalDigits: 2,
        rounding: 0,
        code: "BAM",
        namePlural: "Bosnia-Herzegovina convertible marks"),
    "BDT": Currency(
        symbol: "Tk",
        name: "Bangladeshi Taka",
        symbolNative: "৳",
        decimalDigits: 2,
        rounding: 0,
        code: "BDT",
        namePlural: "Bangladeshi takas"),
    "BGN": Currency(
        symbol: "BGN",
        name: "Bulgarian Lev",
        symbolNative: "лв.",
        decimalDigits: 2,
        rounding: 0,
        code: "BGN",
        namePlural: "Bulgarian leva"),
    "BHD": Currency(
        symbol: "BD",
        name: "Bahraini Dinar",
        symbolNative: "د.ب.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "BHD",
        namePlural: "Bahraini dinars"),
    "BIF": Currency(
        symbol: "FBu",
        name: "Burundian Franc",
        symbolNative: "FBu",
        decimalDigits: 0,
        rounding: 0,
        code: "BIF",
        namePlural: "Burundian francs"),
    "BND": Currency(
        symbol: "BN\$",
        name: "Brunei Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "BND",
        namePlural: "Brunei dollars"),
    "BOB": Currency(
        symbol: "Bs",
        name: "Bolivian Boliviano",
        symbolNative: "Bs",
        decimalDigits: 2,
        rounding: 0,
        code: "BOB",
        namePlural: "Bolivian bolivianos"),
    "BRL": Currency(
        symbol: "R\$",
        name: "Brazilian Real",
        symbolNative: "R\$",
        decimalDigits: 2,
        rounding: 0,
        code: "BRL",
        namePlural: "Brazilian reals"),
    "BWP": Currency(
        symbol: "BWP",
        name: "Botswanan Pula",
        symbolNative: "P",
        decimalDigits: 2,
        rounding: 0,
        code: "BWP",
        namePlural: "Botswanan pulas"),
    "BYR": Currency(
        symbol: "BYR",
        name: "Belarusian Ruble",
        symbolNative: "BYR",
        decimalDigits: 0,
        rounding: 0,
        code: "BYR",
        namePlural: "Belarusian rubles"),
    "BZD": Currency(
        symbol: "BZ\$",
        name: "Belize Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "BZD",
        namePlural: "Belize dollars"),
    "CDF": Currency(
        symbol: "CDF",
        name: "Congolese Franc",
        symbolNative: "FrCD",
        decimalDigits: 2,
        rounding: 0,
        code: "CDF",
        namePlural: "Congolese francs"),
    "CHF": Currency(
        symbol: "CHF",
        name: "Swiss Franc",
        symbolNative: "CHF",
        decimalDigits: 2,
        rounding: 0.05,
        code: "CHF",
        namePlural: "Swiss francs"),
    "CLP": Currency(
        symbol: "CL\$",
        name: "Chilean Peso",
        symbolNative: "\$",
        decimalDigits: 0,
        rounding: 0,
        code: "CLP",
        namePlural: "Chilean pesos"),
    "CNY": Currency(
        symbol: "CN¥",
        name: "Chinese Yuan",
        symbolNative: "CN¥",
        decimalDigits: 2,
        rounding: 0,
        code: "CNY",
        namePlural: "Chinese yuan"),
    "COP": Currency(
        symbol: "CO\$",
        name: "Colombian Peso",
        symbolNative: "\$",
        decimalDigits: 0,
        rounding: 0,
        code: "COP",
        namePlural: "Colombian pesos"),
    "CRC": Currency(
        symbol: "₡",
        name: "Costa Rican Colón",
        symbolNative: "₡",
        decimalDigits: 0,
        rounding: 0,
        code: "CRC",
        namePlural: "Costa Rican colóns"),
    "CVE": Currency(
        symbol: "CV\$",
        name: "Cape Verdean Escudo",
        symbolNative: "CV\$",
        decimalDigits: 2,
        rounding: 0,
        code: "CVE",
        namePlural: "Cape Verdean escudos"),
    "CZK": Currency(
        symbol: "Kč",
        name: "Czech Republic Koruna",
        symbolNative: "Kč",
        decimalDigits: 2,
        rounding: 0,
        code: "CZK",
        namePlural: "Czech Republic korunas"),
    "DJF": Currency(
        symbol: "Fdj",
        name: "Djiboutian Franc",
        symbolNative: "Fdj",
        decimalDigits: 0,
        rounding: 0,
        code: "DJF",
        namePlural: "Djiboutian francs"),
    "DKK": Currency(
        symbol: "Dkr",
        name: "Danish Krone",
        symbolNative: "kr",
        decimalDigits: 2,
        rounding: 0,
        code: "DKK",
        namePlural: "Danish kroner"),
    "DOP": Currency(
        symbol: "RD\$",
        name: "Dominican Peso",
        symbolNative: "RD\$",
        decimalDigits: 2,
        rounding: 0,
        code: "DOP",
        namePlural: "Dominican pesos"),
    "DZD": Currency(
        symbol: "DA",
        name: "Algerian Dinar",
        symbolNative: "د.ج.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "DZD",
        namePlural: "Algerian dinars"),
    "EEK": Currency(
        symbol: "Ekr",
        name: "Estonian Kroon",
        symbolNative: "kr",
        decimalDigits: 2,
        rounding: 0,
        code: "EEK",
        namePlural: "Estonian kroons"),
    "EGP": Currency(
        symbol: "EGP",
        name: "Egyptian Pound",
        symbolNative: "ج.م.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "EGP",
        namePlural: "Egyptian pounds"),
    "ERN": Currency(
        symbol: "Nfk",
        name: "Eritrean Nakfa",
        symbolNative: "Nfk",
        decimalDigits: 2,
        rounding: 0,
        code: "ERN",
        namePlural: "Eritrean nakfas"),
    "ETB": Currency(
        symbol: "Br",
        name: "Ethiopian Birr",
        symbolNative: "Br",
        decimalDigits: 2,
        rounding: 0,
        code: "ETB",
        namePlural: "Ethiopian birrs"),
    "GBP": Currency(
        symbol: "£",
        name: "British Pound Sterling",
        symbolNative: "£",
        decimalDigits: 2,
        rounding: 0,
        code: "GBP",
        namePlural: "British pounds sterling"),
    "GEL": Currency(
        symbol: "GEL",
        name: "Georgian Lari",
        symbolNative: "GEL",
        decimalDigits: 2,
        rounding: 0,
        code: "GEL",
        namePlural: "Georgian laris"),
    "GHS": Currency(
        symbol: "GH₵",
        name: "Ghanaian Cedi",
        symbolNative: "GH₵",
        decimalDigits: 2,
        rounding: 0,
        code: "GHS",
        namePlural: "Ghanaian cedis"),
    "GNF": Currency(
        symbol: "FG",
        name: "Guinean Franc",
        symbolNative: "FG",
        decimalDigits: 0,
        rounding: 0,
        code: "GNF",
        namePlural: "Guinean francs"),
    "GTQ": Currency(
        symbol: "GTQ",
        name: "Guatemalan Quetzal",
        symbolNative: "Q",
        decimalDigits: 2,
        rounding: 0,
        code: "GTQ",
        namePlural: "Guatemalan quetzals"),
    "HKD": Currency(
        symbol: "HK\$",
        name: "Hong Kong Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "HKD",
        namePlural: "Hong Kong dollars"),
    "HNL": Currency(
        symbol: "HNL",
        name: "Honduran Lempira",
        symbolNative: "L",
        decimalDigits: 2,
        rounding: 0,
        code: "HNL",
        namePlural: "Honduran lempiras"),
    "HRK": Currency(
        symbol: "kn",
        name: "Croatian Kuna",
        symbolNative: "kn",
        decimalDigits: 2,
        rounding: 0,
        code: "HRK",
        namePlural: "Croatian kunas"),
    "HUF": Currency(
        symbol: "Ft",
        name: "Hungarian Forint",
        symbolNative: "Ft",
        decimalDigits: 0,
        rounding: 0,
        code: "HUF",
        namePlural: "Hungarian forints"),
    "IDR": Currency(
        symbol: "Rp",
        name: "Indonesian Rupiah",
        symbolNative: "Rp",
        decimalDigits: 0,
        rounding: 0,
        code: "IDR",
        namePlural: "Indonesian rupiahs"),
    "ILS": Currency(
        symbol: "₪",
        name: "Israeli New Sheqel",
        symbolNative: "₪",
        decimalDigits: 2,
        rounding: 0,
        code: "ILS",
        namePlural: "Israeli new sheqels"),
    "INR": Currency(
        symbol: "Rs",
        name: "Indian Rupee",
        symbolNative: "টকা",
        decimalDigits: 2,
        rounding: 0,
        code: "INR",
        namePlural: "Indian rupees"),
    "IQD": Currency(
        symbol: "IQD",
        name: "Iraqi Dinar",
        symbolNative: "د.ع.‏",
        decimalDigits: 0,
        rounding: 0,
        code: "IQD",
        namePlural: "Iraqi dinars"),
    "IRR": Currency(
        symbol: "IRR",
        name: "Iranian Rial",
        symbolNative: "﷼",
        decimalDigits: 0,
        rounding: 0,
        code: "IRR",
        namePlural: "Iranian rials"),
    "ISK": Currency(
        symbol: "Ikr",
        name: "Icelandic Króna",
        symbolNative: "kr",
        decimalDigits: 0,
        rounding: 0,
        code: "ISK",
        namePlural: "Icelandic krónur"),
    "JMD": Currency(
        symbol: "J\$",
        name: "Jamaican Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "JMD",
        namePlural: "Jamaican dollars"),
    "JOD": Currency(
        symbol: "JD",
        name: "Jordanian Dinar",
        symbolNative: "د.أ.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "JOD",
        namePlural: "Jordanian dinars"),
    "JPY": Currency(
        symbol: "¥",
        name: "Japanese Yen",
        symbolNative: "￥",
        decimalDigits: 0,
        rounding: 0,
        code: "JPY",
        namePlural: "Japanese yen"),
    "KES": Currency(
        symbol: "Ksh",
        name: "Kenyan Shilling",
        symbolNative: "Ksh",
        decimalDigits: 2,
        rounding: 0,
        code: "KES",
        namePlural: "Kenyan shillings"),
    "KHR": Currency(
        symbol: "KHR",
        name: "Cambodian Riel",
        symbolNative: "៛",
        decimalDigits: 2,
        rounding: 0,
        code: "KHR",
        namePlural: "Cambodian riels"),
    "KMF": Currency(
        symbol: "CF",
        name: "Comorian Franc",
        symbolNative: "FC",
        decimalDigits: 0,
        rounding: 0,
        code: "KMF",
        namePlural: "Comorian francs"),
    "KRW": Currency(
        symbol: "₩",
        name: "South Korean Won",
        symbolNative: "₩",
        decimalDigits: 0,
        rounding: 0,
        code: "KRW",
        namePlural: "South Korean won"),
    "KWD": Currency(
        symbol: "KD",
        name: "Kuwaiti Dinar",
        symbolNative: "د.ك.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "KWD",
        namePlural: "Kuwaiti dinars"),
    "KZT": Currency(
        symbol: "KZT",
        name: "Kazakhstani Tenge",
        symbolNative: "тңг.",
        decimalDigits: 2,
        rounding: 0,
        code: "KZT",
        namePlural: "Kazakhstani tenges"),
    "LBP": Currency(
        symbol: "LB£",
        name: "Lebanese Pound",
        symbolNative: "ل.ل.‏",
        decimalDigits: 0,
        rounding: 0,
        code: "LBP",
        namePlural: "Lebanese pounds"),
    "LKR": Currency(
        symbol: "SLRs",
        name: "Sri Lankan Rupee",
        symbolNative: "SL Re",
        decimalDigits: 2,
        rounding: 0,
        code: "LKR",
        namePlural: "Sri Lankan rupees"),
    "LTL": Currency(
        symbol: "Lt",
        name: "Lithuanian Litas",
        symbolNative: "Lt",
        decimalDigits: 2,
        rounding: 0,
        code: "LTL",
        namePlural: "Lithuanian litai"),
    "LVL": Currency(
        symbol: "Ls",
        name: "Latvian Lats",
        symbolNative: "Ls",
        decimalDigits: 2,
        rounding: 0,
        code: "LVL",
        namePlural: "Latvian lati"),
    "LYD": Currency(
        symbol: "LD",
        name: "Libyan Dinar",
        symbolNative: "د.ل.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "LYD",
        namePlural: "Libyan dinars"),
    "MAD": Currency(
        symbol: "MAD",
        name: "Moroccan Dirham",
        symbolNative: "د.م.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "MAD",
        namePlural: "Moroccan dirhams"),
    "MDL": Currency(
        symbol: "MDL",
        name: "Moldovan Leu",
        symbolNative: "MDL",
        decimalDigits: 2,
        rounding: 0,
        code: "MDL",
        namePlural: "Moldovan lei"),
    "MGA": Currency(
        symbol: "MGA",
        name: "Malagasy Ariary",
        symbolNative: "MGA",
        decimalDigits: 0,
        rounding: 0,
        code: "MGA",
        namePlural: "Malagasy Ariaries"),
    "MKD": Currency(
        symbol: "MKD",
        name: "Macedonian Denar",
        symbolNative: "MKD",
        decimalDigits: 2,
        rounding: 0,
        code: "MKD",
        namePlural: "Macedonian denari"),
    "MMK": Currency(
        symbol: "MMK",
        name: "Myanma Kyat",
        symbolNative: "K",
        decimalDigits: 0,
        rounding: 0,
        code: "MMK",
        namePlural: "Myanma kyats"),
    "MOP": Currency(
        symbol: "MOP\$",
        name: "Macanese Pataca",
        symbolNative: "MOP\$",
        decimalDigits: 2,
        rounding: 0,
        code: "MOP",
        namePlural: "Macanese patacas"),
    "MUR": Currency(
        symbol: "MURs",
        name: "Mauritian Rupee",
        symbolNative: "MURs",
        decimalDigits: 0,
        rounding: 0,
        code: "MUR",
        namePlural: "Mauritian rupees"),
    "MXN": Currency(
        symbol: "MX\$",
        name: "Mexican Peso",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "MXN",
        namePlural: "Mexican pesos"),
    "MYR": Currency(
        symbol: "RM",
        name: "Malaysian Ringgit",
        symbolNative: "RM",
        decimalDigits: 2,
        rounding: 0,
        code: "MYR",
        namePlural: "Malaysian ringgits"),
    "MZN": Currency(
        symbol: "MTn",
        name: "Mozambican Metical",
        symbolNative: "MTn",
        decimalDigits: 2,
        rounding: 0,
        code: "MZN",
        namePlural: "Mozambican meticals"),
    "NAD": Currency(
        symbol: "N\$",
        name: "Namibian Dollar",
        symbolNative: "N\$",
        decimalDigits: 2,
        rounding: 0,
        code: "NAD",
        namePlural: "Namibian dollars"),
    "NGN": Currency(
        symbol: "₦",
        name: "Nigerian Naira",
        symbolNative: "₦",
        decimalDigits: 2,
        rounding: 0,
        code: "NGN",
        namePlural: "Nigerian nairas"),
    "NIO": Currency(
        symbol: "C\$",
        name: "Nicaraguan Córdoba",
        symbolNative: "C\$",
        decimalDigits: 2,
        rounding: 0,
        code: "NIO",
        namePlural: "Nicaraguan córdobas"),
    "NOK": Currency(
        symbol: "Nkr",
        name: "Norwegian Krone",
        symbolNative: "kr",
        decimalDigits: 2,
        rounding: 0,
        code: "NOK",
        namePlural: "Norwegian kroner"),
    "NPR": Currency(
        symbol: "NPRs",
        name: "Nepalese Rupee",
        symbolNative: "नेरू",
        decimalDigits: 2,
        rounding: 0,
        code: "NPR",
        namePlural: "Nepalese rupees"),
    "NZD": Currency(
        symbol: "NZ\$",
        name: "New Zealand Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "NZD",
        namePlural: "New Zealand dollars"),
    "OMR": Currency(
        symbol: "OMR",
        name: "Omani Rial",
        symbolNative: "ر.ع.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "OMR",
        namePlural: "Omani rials"),
    "PAB": Currency(
        symbol: "B/.",
        name: "Panamanian Balboa",
        symbolNative: "B/.",
        decimalDigits: 2,
        rounding: 0,
        code: "PAB",
        namePlural: "Panamanian balboas"),
    "PEN": Currency(
        symbol: "S/.",
        name: "Peruvian Nuevo Sol",
        symbolNative: "S/.",
        decimalDigits: 2,
        rounding: 0,
        code: "PEN",
        namePlural: "Peruvian nuevos soles"),
    "PHP": Currency(
        symbol: "₱",
        name: "Philippine Peso",
        symbolNative: "₱",
        decimalDigits: 2,
        rounding: 0,
        code: "PHP",
        namePlural: "Philippine pesos"),
    "PKR": Currency(
        symbol: "PKRs",
        name: "Pakistani Rupee",
        symbolNative: "₨",
        decimalDigits: 0,
        rounding: 0,
        code: "PKR",
        namePlural: "Pakistani rupees"),
    "PLN": Currency(
        symbol: "zł",
        name: "Polish Zloty",
        symbolNative: "zł",
        decimalDigits: 2,
        rounding: 0,
        code: "PLN",
        namePlural: "Polish zlotys"),
    "PYG": Currency(
        symbol: "₲",
        name: "Paraguayan Guarani",
        symbolNative: "₲",
        decimalDigits: 0,
        rounding: 0,
        code: "PYG",
        namePlural: "Paraguayan guaranis"),
    "QAR": Currency(
        symbol: "QR",
        name: "Qatari Rial",
        symbolNative: "ر.ق.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "QAR",
        namePlural: "Qatari rials"),
    "RON": Currency(
        symbol: "RON",
        name: "Romanian Leu",
        symbolNative: "RON",
        decimalDigits: 2,
        rounding: 0,
        code: "RON",
        namePlural: "Romanian lei"),
    "RSD": Currency(
        symbol: "din.",
        name: "Serbian Dinar",
        symbolNative: "дин.",
        decimalDigits: 0,
        rounding: 0,
        code: "RSD",
        namePlural: "Serbian dinars"),
    "RUB": Currency(
        symbol: "RUB",
        name: "Russian Ruble",
        symbolNative: "руб.",
        decimalDigits: 2,
        rounding: 0,
        code: "RUB",
        namePlural: "Russian rubles"),
    "RWF": Currency(
        symbol: "RWF",
        name: "Rwandan Franc",
        symbolNative: "FR",
        decimalDigits: 0,
        rounding: 0,
        code: "RWF",
        namePlural: "Rwandan francs"),
    "SAR": Currency(
        symbol: "SR",
        name: "Saudi Riyal",
        symbolNative: "ر.س.‏",
        decimalDigits: 2,
        rounding: 0,
        code: "SAR",
        namePlural: "Saudi riyals"),
    "SDG": Currency(
        symbol: "SDG",
        name: "Sudanese Pound",
        symbolNative: "SDG",
        decimalDigits: 2,
        rounding: 0,
        code: "SDG",
        namePlural: "Sudanese pounds"),
    "SEK": Currency(
        symbol: "Skr",
        name: "Swedish Krona",
        symbolNative: "kr",
        decimalDigits: 2,
        rounding: 0,
        code: "SEK",
        namePlural: "Swedish kronor"),
    "SGD": Currency(
        symbol: "S\$",
        name: "Singapore Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "SGD",
        namePlural: "Singapore dollars"),
    "SOS": Currency(
        symbol: "Ssh",
        name: "Somali Shilling",
        symbolNative: "Ssh",
        decimalDigits: 0,
        rounding: 0,
        code: "SOS",
        namePlural: "Somali shillings"),
    "SYP": Currency(
        symbol: "SY£",
        name: "Syrian Pound",
        symbolNative: "ل.س.‏",
        decimalDigits: 0,
        rounding: 0,
        code: "SYP",
        namePlural: "Syrian pounds"),
    "THB": Currency(
        symbol: "฿",
        name: "Thai Baht",
        symbolNative: "฿",
        decimalDigits: 2,
        rounding: 0,
        code: "THB",
        namePlural: "Thai baht"),
    "TND": Currency(
        symbol: "DT",
        name: "Tunisian Dinar",
        symbolNative: "د.ت.‏",
        decimalDigits: 3,
        rounding: 0,
        code: "TND",
        namePlural: "Tunisian dinars"),
    "TOP": Currency(
        symbol: "T\$",
        name: "Tongan Paʻanga",
        symbolNative: "T\$",
        decimalDigits: 2,
        rounding: 0,
        code: "TOP",
        namePlural: "Tongan paʻanga"),
    "TRY": Currency(
        symbol: "TL",
        name: "Turkish Lira",
        symbolNative: "TL",
        decimalDigits: 2,
        rounding: 0,
        code: "TRY",
        namePlural: "Turkish Lira"),
    "TTD": Currency(
        symbol: "TT\$",
        name: "Trinidad and Tobago Dollar",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "TTD",
        namePlural: "Trinidad and Tobago dollars"),
    "TWD": Currency(
        symbol: "NT\$",
        name: "New Taiwan Dollar",
        symbolNative: "NT\$",
        decimalDigits: 2,
        rounding: 0,
        code: "TWD",
        namePlural: "New Taiwan dollars"),
    "TZS": Currency(
        symbol: "TSh",
        name: "Tanzanian Shilling",
        symbolNative: "TSh",
        decimalDigits: 0,
        rounding: 0,
        code: "TZS",
        namePlural: "Tanzanian shillings"),
    "UAH": Currency(
        symbol: "₴",
        name: "Ukrainian Hryvnia",
        symbolNative: "₴",
        decimalDigits: 2,
        rounding: 0,
        code: "UAH",
        namePlural: "Ukrainian hryvnias"),
    "UGX": Currency(
        symbol: "USh",
        name: "Ugandan Shilling",
        symbolNative: "USh",
        decimalDigits: 0,
        rounding: 0,
        code: "UGX",
        namePlural: "Ugandan shillings"),
    "UYU": Currency(
        symbol: "\$U",
        name: "Uruguayan Peso",
        symbolNative: "\$",
        decimalDigits: 2,
        rounding: 0,
        code: "UYU",
        namePlural: "Uruguayan pesos"),
    "UZS": Currency(
        symbol: "UZS",
        name: "Uzbekistan Som",
        symbolNative: "UZS",
        decimalDigits: 0,
        rounding: 0,
        code: "UZS",
        namePlural: "Uzbekistan som"),
    "VEF": Currency(
        symbol: "Bs.F.",
        name: "Venezuelan Bolívar",
        symbolNative: "Bs.F.",
        decimalDigits: 2,
        rounding: 0,
        code: "VEF",
        namePlural: "Venezuelan bolívars"),
    "VND": Currency(
        symbol: "₫",
        name: "Vietnamese Dong",
        symbolNative: "₫",
        decimalDigits: 0,
        rounding: 0,
        code: "VND",
        namePlural: "Vietnamese dong"),
    "XAF": Currency(
        symbol: "FCFA",
        name: "CFA Franc BEAC",
        symbolNative: "FCFA",
        decimalDigits: 0,
        rounding: 0,
        code: "XAF",
        namePlural: "CFA francs BEAC"),
    "XOF": Currency(
        symbol: "CFA",
        name: "CFA Franc BCEAO",
        symbolNative: "CFA",
        decimalDigits: 0,
        rounding: 0,
        code: "XOF",
        namePlural: "CFA francs BCEAO"),
    "YER": Currency(
        symbol: "YR",
        name: "Yemeni Rial",
        symbolNative: "ر.ي.‏",
        decimalDigits: 0,
        rounding: 0,
        code: "YER",
        namePlural: "Yemeni rials"),
    "ZAR": Currency(
        symbol: "R",
        name: "South African Rand",
        symbolNative: "R",
        decimalDigits: 2,
        rounding: 0,
        code: "ZAR",
        namePlural: "South African rand"),
    "ZMK": Currency(
        symbol: "ZK",
        name: "Zambian Kwacha",
        symbolNative: "ZK",
        decimalDigits: 0,
        rounding: 0,
        code: "ZMK",
        namePlural: "Zambian kwachas")
  };

  static String _staleRates =
      '{"USDAED":3.673102, "USDAFN":79.850278, "USDALL":108.87015, "USDAMD":476.180076, "USDANG":1.78505, "USDAOA":346.555499, "USDARS":42.460981, "USDAUD":1.420498, "USDAWG":1.79975, "USDAZN":1.705022, "USDBAM":1.742903, "USDBBD":2.01975, "USDBDT":84.513007, "USDBGN":1.744295, "USDBHD":0.377033, "USDBIF":1851, "USDBMD":1, "USDBND":1.35045, "USDBOB":6.91285, "USDBRL":3.736403, "USDBSD":1.00025, "USDBTC":9.7426821e-5, "USDBTN":68.914096, "USDBWP":10.577991, "USDBYN":2.017401, "USDBYR":19600, "USDBZD":2.01575, "USDCAD":1.31175, "USDCDF":1665.501438, "USDCHF":0.981695, "USDCLF":0.024959, "USDCLP":688.601415, "USDCNY":6.880984, "USDCOP":3174.15, "USDCRC":574.735041, "USDCUC":1, "USDCUP":26.5, "USDCVE":98.2225, "USDCZK":22.777983, "USDDJF":177.719732, "USDDKK":6.65835, "USDDOP":51.044952, "USDDZD":119.425029, "USDEGP":16.611036, "USDERN":14.999632, "USDETB":29.005019, "USDEUR":0.891765, "USDFJD":2.12195, "USDFKP":0.800805, "USDGBP":0.801702, "USDGEL":2.875, "USDGGP":0.801643, "USDGHS":5.389402, "USDGIP":0.800805, "USDGMD":49.96494, "USDGNF":9237.50529, "USDGTQ":7.66535, "USDGYD":208.824996, "USDHKD":7.81025, "USDHNL":24.649688, "USDHRK":6.587399, "USDHTG":94.0615, "USDHUF":290.067997, "USDIDR":13938, "USDILS":3.527504, "USDIMP":0.801643, "USDINR":68.922497, "USDIQD":1190, "USDIRR":42104.999767, "USDISK":124.74986, "USDJEP":0.801643, "USDJMD":134.620006, "USDJOD":0.707695, "USDJPY":107.892498, "USDKES":103.58965, "USDKGS":69.647987, "USDKHR":4083.000157, "USDKMF":438.825034, "USDKPW":900.063955, "USDKRW":1176.000169, "USDKWD":0.3043, "USDKYD":0.833405, "USDKZT":385.740314, "USDLAK":8685.000304, "USDLBP":1507.949971, "USDLKR":175.87028, "USDLRD":201.624972, "USDLSL":13.84002, "USDLTL":2.952741, "USDLVL":0.60489, "USDLYD":1.404975, "USDMAD":9.59335, "USDMDL":17.525503, "USDMGA":3607.529093, "USDMKD":54.660489, "USDMMK":1518.103721, "USDMNT":2664.490574, "USDMOP":8.04445, "USDMRO":357.000346, "USDMUR":35.919714, "USDMVR":15.450255, "USDMWK":759.935024, "USDMXN":19.06545, "USDMYR":4.111973, "USDMZN":61.814974, "USDNAD":13.840303, "USDNGN":359.999783, "USDNIO":33.496149, "USDNOK":8.60639, "USDNPR":110.245032, "USDNZD":1.47605, "USDOMR":0.384962, "USDPAB":1.00025, "USDPEN":3.28495, "USDPGK":3.389929, "USDPHP":51.131984, "USDPKR":159.897773, "USDPLN":3.78825, "USDPYG":5977.550349, "USDQAR":3.64175, "USDRON":4.209098, "USDRSD":105.009683, "USDRUB":63.102903, "USDRWF":910, "USDSAR":3.750604, "USDSBD":8.27135, "USDSCR":13.743019, "USDSDG":45.114494, "USDSEK":9.40942, "USDSGD":1.360703, "USDSHP":1.320897, "USDSLL":9249.999993, "USDSOS":580.000015, "USDSRD":7.457987, "USDSTD":21560.79, "USDSVC":8.75025, "USDSYP":515.000086, "USDSZL":13.840272, "USDTHB":30.87022, "USDTJS":9.430199, "USDTMT":3.5, "USDTND":2.86375, "USDTOP":2.267896, "USDTRY":5.687296, "USDTTD":6.77465, "USDTWD":31.049788, "USDTZS":2299.698844, "USDUAH":25.783984, "USDUGX":3695.198022, "USDUSD":1, "USDUYU":35.129727, "USDUZS":8629.999832, "USDVEF":9.987503, "USDVND":23230.6, "USDVUV":114.780027, "USDWST":2.602797, "USDXAF":584.559721, "USDXAG":0.061031, "USDXAU":0.000701, "USDXCD":2.70255, "USDXDR":0.723833, "USDXOF":591.500088, "USDXPF":106.698863, "USDYER":250.303594, "USDZAR":13.877903, "USDZMK":9001.195989, "USDZMW":12.825504, "USDZWL":322.000001}';

  static Map getCurrencies() {
    return _currencies;
  }

  static getDefaultTopCurrency() {
    return _currencies["GBP"];
  }

  static getDefaultBottomCurrency() {
    return _currencies["NGN"];
  }

  static getStaleRates() {
    return _staleRates;
  }
}
